# Generated by Django 4.2.5 on 2023-10-13 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, '최소 세 글자 이상은 입력해주셔야 합니다.')])),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10, '최소 10글자 이상은 입력해주셔야 합니다.')])),
                ('link', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('ceo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_category', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(validators=[django.core.validators.MinLengthValidator(10, '최소 10 글자 이상은 입력해주셔야 합니다.')])),
                ('content_pros', models.TextField(validators=[django.core.validators.MinLengthValidator(30, '최소 30 글자 이상은 입력해주셔야 합니다.')])),
                ('content_cons', models.TextField(validators=[django.core.validators.MinLengthValidator(30, '최소 30 글자 이상은 입력해주셔야 합니다.')])),
                ('content_hope', models.TextField(validators=[django.core.validators.MinLengthValidator(30, '최소 30 글자 이상은 입력해주셔야 합니다.')])),
                ('star', models.IntegerField()),
                ('star_1', models.IntegerField()),
                ('star_2', models.IntegerField()),
                ('star_3', models.IntegerField()),
                ('star_4', models.IntegerField()),
                ('star_5', models.IntegerField()),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.board')),
            ],
        ),
    ]
